/**
 * The opening's handwriting (src/features/intro/greeting-paths.ts): the
 * greeting in each language as the outlines of its letters, so the page can
 * draw them stroke by stroke the way a hand writes, with no font to load.
 *
 * The letters are Great Vibes (Robert Leuschke, SIL Open Font License 1.1),
 * a flowing script with Cyrillic; kerning is applied as the font asks. It has
 * no ғ ҷ қ ӣ ӯ ҳ, which is why only these fixed greetings are drawn from it —
 * a person's name is written in a face that has the whole Tajik alphabet
 * (welcome-transition.tsx).
 *
 *   npm i --no-save opentype.js@1.3.4 && node scripts/brand/greeting-paths.mjs
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import opentype from "opentype.js";

const FONT = "https://fonts.gstatic.com/s/greatvibes/v21/RWmMoKWR9v4ksMfaWd_JN-XC.ttf";

const GREETINGS = {
  tg: { hello: "Ассалому алайкум", welcome: "Хуш омадед" },
  ru: { hello: "Здравствуйте", welcome: "Добро пожаловать" },
  en: { hello: "Hello", welcome: "Welcome" },
};

// One unit of the drawing is a hundredth of the letters' size.
const SIZE = 100;
const PAD = 3;

const response = await fetch(FONT);
if (!response.ok) throw new Error(`Great Vibes: ${response.status}`);
const font = opentype.parse(await response.arrayBuffer());

/** A glyph's outline as a path, rounded to whole units and written in relative steps. */
function pathData(path, ox, oy) {
  const r = Math.round;
  let out = "";
  let cx = 0;
  let cy = 0;
  let sx = 0;
  let sy = 0;
  let first = true;
  const num = (v) => (v < 0 || !/\d$/.test(out) ? String(v) : ` ${v}`);
  const pair = (x, y) => {
    out += num(x);
    out += num(y);
  };
  for (const c of path.commands) {
    if (c.type === "Z") {
      out += "z";
      cx = sx;
      cy = sy;
      continue;
    }
    const x = r(c.x - ox);
    const y = r(c.y - oy);
    if (c.type === "M") {
      out += first ? "M" : "m";
      pair(first ? x : x - cx, first ? y : y - cy);
      first = false;
      sx = x;
      sy = y;
    } else if (c.type === "L") {
      out += "l";
      pair(x - cx, y - cy);
    } else if (c.type === "C") {
      out += "c";
      pair(r(c.x1 - ox) - cx, r(c.y1 - oy) - cy);
      pair(r(c.x2 - ox) - cx, r(c.y2 - oy) - cy);
      pair(x - cx, y - cy);
    } else if (c.type === "Q") {
      out += "q";
      pair(r(c.x1 - ox) - cx, r(c.y1 - oy) - cy);
      pair(x - cx, y - cy);
    }
    cx = x;
    cy = y;
  }
  return out;
}

function line(text) {
  const glyphs = [];
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  font.forEachGlyph(text, 0, 0, SIZE, { kerning: true }, (glyph, x, y, size) => {
    const path = glyph.getPath(x, y, size);
    if (!path.commands.length) return;
    const box = path.getBoundingBox();
    minX = Math.min(minX, box.x1);
    minY = Math.min(minY, box.y1);
    maxX = Math.max(maxX, box.x2);
    maxY = Math.max(maxY, box.y2);
    glyphs.push({ path, left: box.x1 });
  });
  const ox = Math.floor(minX) - PAD;
  const oy = Math.floor(minY) - PAD;
  const width = Math.ceil(maxX) - ox + PAD;
  const height = Math.ceil(maxY) - oy + PAD;
  return {
    text,
    width,
    height,
    // `at`: where the letter starts along the line, 0 to 1 — when the hand reaches it.
    glyphs: glyphs.map((g) => ({ at: Math.round(((g.left - ox) / width) * 1000) / 1000, d: pathData(g.path, ox, oy) })),
  };
}

const data = Object.fromEntries(
  Object.entries(GREETINGS).map(([locale, lines]) => [locale, { hello: line(lines.hello), welcome: line(lines.welcome) }])
);

const target = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "src", "features", "intro", "greeting-paths.ts");
writeFileSync(
  target,
  `/**
 * Generated by scripts/brand/greeting-paths.mjs — do not edit by hand.
 *
 * The greeting in each language, letter by letter, as outlines of Great Vibes
 * (SIL Open Font License 1.1) at 100 units to the letters' size.
 */
import type { Locale } from "@/lib/i18n/text";

export interface ScriptLine {
  text: string;
  width: number;
  height: number;
  glyphs: { at: number; d: string }[];
}

export const GREETING_PATHS: Record<Locale, { hello: ScriptLine; welcome: ScriptLine }> = ${JSON.stringify(data, null, 2)};
`
);
console.log(`wrote ${target}`);
